### ISSUE TITLE
backendで npm run dev をしたらエラーになってしまう

### ISSUE THREAD

**Issue by atsushi0124** [atsushi0124/memoApp#1]
DBに接続する方法がわからず、調べていたのですが、backendのルートディレクトリの方で、npm run dev をするとエラーになってしまいました。
このエラーの解決方法がわからなくて、困っています。

エラー文は下記の通りです。

ooshimaatsushi@ooshimaatsushinoMacBook-Pro backend % npm run dev

> mavs-task-backend@1.0.0 dev
> nodemon src/index.js

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/index.js`
file:///Users/ooshimaatsushi/Documents/works/mavs-task/mavs-task/backend/src/models/index.js:4
import config from '../config/config.json' assert { type: 'json' };
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (node:internal/modules/esm/translators:146:18)
[nodemon] app crashed - waiting for file changes before starting...

<img width="767" alt="スクリーンショット 2023-12-25 14 56 26" src="https://github.com/atsushi0124/mavs-task/assets/71283865/c0b39fd5-bddc-402c-bf07-2bd433b3f0b5">

**試した事**
下記の記事で見たところ、構文は間違っていないと思いました。
https://sosukesuzuki.dev/posts/import-assertions/

node.jsのバージョンは
v16.10.0
なので、問題ないと思いました。

エラーを検索して調べたのですが、分からなかったので、ChatGPTに聞いたところ、

「package.jsonの設定：プロジェクトのpackage.jsonファイルに"type": "module"が設定されていることを確認してください。この設定がないと、Node.jsはコードをCommonJSモジュールとして扱い、ESMの構文がサポートされません。」
と返答がありました。

config.jsonに"type": "moduleがなかったので、追加をしたところ、同じエラーが返ってきてしまいました。

ご教示のほど、よろしくお願いたします。

**Comment by sho-mavs** [comment]
上記を確認し、個別でbackendディレクトリにて`npm run dev`したら本件が発生することは確かに確認しました‥

ただ、課題のREADME.mdの起動の方法は個別backend起動ではなく、以下の記載があります。
https://github.com/atsushi0124/mavs-task?tab=readme-ov-file#docker-%E3%82%92%E8%B5%B7%E5%8B%95%E3%83%AB%E3%83%BC%E3%83%88%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%81%A7%E5%AE%9F%E8%A1%8C

> Docker を起動（ルートディレクトリで実行）
> Docker Desktopを起動しておきます。
> 
> cd ../
> docker compose up --build

「docker compose up --build」で起動した場合は、こちらの環境では正常に起動出来ましたので、
こちらの起動方法でお試しいただければと思います‥！
