### ISSUE TITLE
データの受け渡しで、行き詰まっています。

### ISSUE THREAD

**Issue by atsushi0124** [atsushi0124/memoApp#3]
**わからないこと**
メモを追加する画面で、保存ボタンを押した際にどうやって一覧画面にデータを渡していいかわからないです。

pagesのフォルダの中で、データをやり取りしていいのか？
または、componentsの中にファイルを作成し、一度そのファイルでデータを取得し、返すのがいいのかを教えていただきたいです。

みていた記事のURLを見失ってしまいました...申し訳ありません。
そこに書かれていたのは、「pagesのフォルダにあるファイル同士で、propsの受け渡しはしてはいけない」というようなことが書かれていました。

確かに、pagesのフォルダにあるファイルはそのままURLのパスになってしまうので、データの受け渡しはしない方がいいのかなと思いました。

私の中では、componentsの中にあるファイルは複数のファイルで共通して使うものと認識があります。
間違っていたらすみません。

あまりうまく言語化ができないのですが、propsで渡ってきた値を加工して戻り値として出せるのかを教えていただきたいです。
よろしくお願いいたします。

**Comment by sho-mavs** [comment]
こちらの理解が誤っていたらご指摘いただければと思いますが、
Figmaで作成いただいた画面デザインも改めて確認させていただいてますが、
「メモ一覧画面」と「メモ追加画面」は**別画面で作成する**という認識で相違はございませんでしょうか？
 → 一覧画面と追加画面はそれぞれpageフォルダ内にvueファイルが作成されることになると思っています。

上記の認識で相違が無い場合ですが、画面の導線的に以下の流れになると思っています！
この流れであれば、データの受け渡しとか意識しなくても良いと思います。

1. 「メモ一覧画面」に遷移。その際、初期表示時にDBからデータを取得
2. 「追加」ボタン押下
3. 「メモ追加画面」に遷移。タイトル・本文を設定し、「保存」ボタンを押下
4.  「保存」後、上記の「1.」と同じ動作になる。 
※ 上記「4.」でデータを再取得すれば、保存したメモデータが一覧に表示されることになるため

ちなみにcomponentsは、実案件の取り決めで変わることがあるかもしれませんが、
おっしゃる通り、複数ファイルで呼ばれるものをコンポーネント化（部品化）したりするのに使ったりすることが多いかもしれません‥！
