### ISSUE TITLE
メモ一覧画面で「ゴミ箱アイコン」を押すと「削除ボタン」と「キャンセルボタン」を表示したいです。

### ISSUE THREAD

**Issue by atsushi0124** [atsushi0124/memoApp#5]
一旦動くコードはできました。
しかし、今のコードでは似たような処理を2回書いてしまっています。
せっかくNuxtで書いているのに、普通のjsっぽく書いてしまっているのでこのコードをどうしたらわかりやすいコードになるのかアドバイスをいただきたいです。
また、このコードをコンポーネントにまとめていいのかをお聞きしたいです。

よろしくお願いおいたします。

`
// DOM要素への参照を作成
const deleteIcon = ref(null);
const cancelBtn = ref(null);
const deleteBtn = ref(null);

// ゴミ箱アイコンの削除
const MemoDelete = () => {
  // deleteIconを非表示にし、cancelBtnとdeleteBtnを表示
  if (deleteIcon.value) {
    deleteIcon.value.classList.add("deleteIcon_none");
  }
  if (cancelBtn.value && deleteBtn.value) {
    cancelBtn.value.classList.remove("none");
    deleteBtn.value.classList.remove("none");
  }
  return deleteIcon.value;
};

// キャンセルボタンを押した時にゴミ箱アイコンを表示
const cancel = () => {
  if (deleteIcon.value) {
    deleteIcon.value.classList.remove("deleteIcon_none");
  }
  if (cancelBtn.value && deleteBtn.value) {
    cancelBtn.value.classList.add("none");
    deleteBtn.value.classList.add("none");
  }
};`

**Comment by sho-mavs** [comment]
該当部分のソースを確認しました！ CSSのスタイルを切り替えて実現したと理解しました。

単純にゴミ箱アイコンの表示/非表示を変数(ref)に持たせて、その変数の状態(true/falseで十分)に応じて
v-ifで `ゴミ箱アイコン` or `削除ボタンとキャンセルボタン` と表示するものを切り替えれば良いのかと思いますが、
いかがでしょうか？

🔸v-if
https://handson.vuejs-jp.org/v-if.html

**Comment by atsushi0124** [comment]
こちらの回答もありがとうございます！
添付していただいた資料で実現できそうなので、やってみます！

本当にありがとうございます！

**Comment by atsushi0124** [comment]
無事に実装することができました！
ありがとうございます！

対応していただきありがとうございます！

こちらクローズさせていただきます！
