### ISSUE TITLE
メモの更新が実装できなくて、はまってしまいました。

### ISSUE THREAD

**Issue by atsushi0124** [atsushi0124/memoApp#7]
行いたい処理としては、メモIDが記事にある場合は更新処理をしたいです。

🔸はまっている箇所
**フロントエンド**
chrome側では、エラーはないのでバックエンドにapiを叩けていると思います。
api実行後のlogを見ると0になっているので、バックエンド側に問題があると思っています。

バックエンドのArticleService.jsのところで、更新処理がうまくいっていないともい、色々試したのですが、エラーを解決することが出来ませんでした。

お手隙の際にご確認していただきたいです。
よろしくお願いいたします。

🔸フロントエンド (createArticle.vue)
// メモの更新
const updateMemo = handleSubmit(async () => {
  try {
    // const { signin } = await useFetch<SignInResponse>
    console.log(memoTitle.value, memoDesc.value);
    const { data } = await useFetch<AddMemoResponse>(
      `${apiBaseUrl}/updateArtic/updateArticle`,
      {
        method: "POST",
        headers: {
          authorization: token,
        },
        body: JSON.stringify({
          title: memoTitle.value,
          content: memoDesc.value,
          user_id: user_id,
          memo_id: memo_id,
        }),
      }
    );
    console.log(data.value);
    $router.push("/");
  } catch (error) {
    console.log(error);
  }
});

if (userStore.memo_id) {
  console.log(`👹${userStore.memo_id}`);
  viewMemo();
}

const addUp = () => {
  if (userStore.memo_id) {
    updateMemo(); //メモIDがある場合、更新処理をする関数を実行
  } else {
    addMemo();  //メモIDがない場合、新規追加をする関数を実行
  }
};

🔸バックエンド 
🔸(updateArticle.router.js)　＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
import ArticleService from '../../services/articles/ArticleService.js';
import express from 'express';
import authenticate from '../../middleware/authenticate.js';

const router = express.Router();
const articleService = new ArticleService();
/**
 * メモ削除
 */
router.post('/updateArticle', authenticate, async (req, res, next) => {
  try {
    const { user_id, memo_id, memo_title, memo_desc } = req.body;
    console.info(`upDate 👹.router=========== ${memo_id} =============================`);  //ここではメモIDを取得できている

    // メモを更新
    const updateArticle = await articleService.updateArticle(
      user_id,
      memo_id,
      memo_title,
      memo_desc
    );

    const body = {
      memo_id: updateArticle.id,
      title: updateArticle.title,
      content: updateArticle.content,
    };
    console.log(`👹  ${body.title}`);  //logではundefindになってしまう。
    res.status(200).json(body.title);
  } catch (error) {
    console.error(error);
    res.status(500).json({});
  }
});

export default router;

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

🔸ArticleService.js
  async updateArticle(user_id, memo_id, memo_title, memo_desc) {
    try {
      const articleData = {
        title: memo_title,
        content: memo_desc,
      };

      const [updatedRows] = await db.Articles.update(articleData, {
        where: {
          id: memo_id,
          author_id: user_id,
        },
      });

      console.log(`${updatedRows} rows updated.`);
      return updatedRows;
    } catch (error) {
      console.error('Update failed:', error);
      throw error;
    }
  }

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

🔸apiサーバーのログ
2024-01-16 20:55:46 Executing (default): SELECT "id", "title", "content", "author_id", "created_at", "updated_at", "created_at" AS "createdAt", "updated_at" AS "updatedAt" FROM "articles" AS "articles" WHERE "articles"."id" = 25 AND "articles"."author_id" = 1;
2024-01-16 20:55:55 upDate 👹.router=========== 25 =============================
2024-01-16 20:55:55 0 rows updated.
2024-01-16 20:55:55 👹  undefined
2024-01-16 20:55:55 Executing (default): SELECT "id", "title", "content", "author_id", "created_at", "updated_at", "created_at" AS "createdAt", "updated_at" AS "updatedAt" FROM "articles" AS "articles" WHERE "articles"."author_id" = 1;

**Comment by sho-mavs** [comment]
本件、確認しました！

以下、更新処理が実施できていない原因のあるところを抜粋しました。
リクエストボディの内容で差異がある部分があるので、よく見比べてみてください。

🔸フロントエンド (createArticle.vue)
```
body: JSON.stringify({
  title: memoTitle.value,
  content: memoDesc.value,
  user_id: user_id,
  memo_id: memo_id,
}),
```

🔸バックエンド (updateArticle.router.js)
`const { user_id, memo_id, memo_title, memo_desc } = req.body;`

**Comment by atsushi0124** [comment]
夜分遅くに確認していただき、ありがとうございます！
ご指摘いただいた、差異の箇所を理解することが出来ました。
本当にありがとうございます！

試してみます！

**Comment by atsushi0124** [comment]
更新することが出来ました！！
夜分遅くに対応していただき、本当にありがとうございました！
解決することが出来ましたので、closeさせていただきます！
